# Generated by Django 2.1.7 on 2019-03-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Service')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Stylist')),
            ],
        ),
        migrations.AddField(
            model_name='stylist',
            name='services',
            field=models.ManyToManyField(through='ticket.StylistService', to='ticket.Service'),
        ),
    ]
