# Generated by Django 2.1.7 on 2019-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190305_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
